work_dir: ./work_dir/nwucla/joint_motion

# feeder
feeder: feeders.feeder_ucla.Feeder
train_feeder_args:
  data_path: joint_motion
  label_path: train
  debug: False
  random_choose: True
  random_shift: False
  random_move: False
  window_size: 52
  normalization: False
  repeat: 5

test_feeder_args:
  data_path: joint_motion
  label_path: val
  debug: False


# model
model: model.lagcn.Model
model_args:
  num_class: 12
  num_point: 18
  num_person: 1
  graph: graph.ucla.Graph
  graph_args:
    labeling_mode: 'spatial'
  examplar: graph.cls_examplar.CLSExamplar
  examplar_args:
    topo_str: "what_will_[J]_act_like_when_[C]-with-punctuation"
    base_dir: cls_matrix_NWUCLA

#optim
weight_decay: 0.00001
base_lr: 0.1
lr_decay_rate: 0.1
step: [50]

# training
device: 0
batch_size: 32
test_batch_size: 64
num_epoch: 80
nesterov: True
warm_up_epoch: 5
